import { StudyKit } from "./types";

export const PRE_BUILT_KITS: StudyKit[] = [
  {
    document: {
      id: "doc_photosynthesis",
      user_id: "user_test",
      title: "Photosynthesis & Cell Biology",
      raw_text_content: "Photosynthesis is the highly coordinated biological process by which green plants, algae, and certain bacteria convert radiant light energy from the sun into stable chemical energy stored in glucose molecules. This essential conversion occurs inside specialized double-membrane organelles called chloroplasts, which house green pigment systems known as chlorophyll. Chlorophyll molecules absorb specific light wavelengths to excite electrons, initiating water oxidation that generates free gaseous oxygen as a metabolic byproduct. The process is divided into light-dependent thylakoid reactions that yield core energy currencies (ATP and NADPH) and the light-independent Calvin cycle inside the stroma that fixes gaseous carbon dioxide into structural triose-phosphate sugars.",
      upload_date: "2026-06-12"
    },
    summary: {
      id: "sum_photosynthesis",
      document_id: "doc_photosynthesis",
      quick_read_json: [
        "Photosynthesis converts renewable solar/light energy into stable chemical fuel (glucose).",
        "The reaction requires three critical elements: Carbon Dioxide (CO₂), Water (H₂O), and sunlight.",
        "It releases free gaseous Oxygen (O₂) into the environment as a vital byproduct.",
        "Occurs inside chloroplast organelles, utilizing chlorophyll pigments to excite high-energy electrons."
      ],
      deep_dive_json: {
        notes: [
          "Organized into thylakoid-bound light-dependent reactions and stroma-bound Calvin cycle reactions.",
          "Water molecules are oxidized (split) at Photosystem II to replace excited chlorophyll electrons.",
          "The chemical system requires a Proton motive gradient across the thylakoid membrane to drive ATP synthesis."
        ],
        formulas: [
          "Chemical equation: 6CO₂ + 6H₂O + photons ➔ C₆H₁₂O₆ + 6O₂",
          "Proton gradient driver: Δp = ΔΨ - (2.3RT/F)ΔpH"
        ],
        definitions: [
          { term: "Chloroplast", definition: "A double-membrane cell structure in plants hosting chlorophyll-mediated photosynthesis." },
          { term: "Thylakoid", definition: "Flattened membrane sacs inside chloroplasts where the light-harvesting reactions occur." },
          { term: "Stroma", definition: "The fluid-filled background space surrounding thylakoid systems where carbon fixation occurs." }
        ]
      },
      eli5_text: "Think of a leaf like a tiny solar-powered bakery! Sunlight is the power outlet, Water and Carbon Dioxide are flour and milk. The tiny chef 'Chlorophyll' mixes them together in the chloroplast oven to bake warm 'Glucose' cookies. When the baking is finished, the chef opens the window to let fresh 'Oxygen' air blow outside so we can breathe!"
    },
    flashcards: [
      {
        id: "fc_photo_1",
        document_id: "doc_photosynthesis",
        question_text: "Where do the light-dependent reactions of photosynthesis specifically happen?",
        answer_text: "Within the thylakoid membranes inside chloroplasts.",
        review_status: "mastered"
      },
      {
        id: "fc_photo_2",
        document_id: "doc_photosynthesis",
        question_text: "What pigment is responsible for absorption of physical light energy?",
        answer_text: "Chlorophyll, which gives plant foliage its green coloration.",
        review_status: "learning"
      },
      {
        id: "fc_photo_3",
        document_id: "doc_photosynthesis",
        question_text: "What gas is produced during water photolysis and released as a byproduct?",
        answer_text: "Gaseous diatomic oxygen (O₂).",
        review_status: "learning"
      },
      {
        id: "fc_photo_4",
        document_id: "doc_photosynthesis",
        question_text: "What are the two primary energy-carrying products generated by light reactions?",
        answer_text: "ATP (Adenosine Triphosphate) and NADPH.",
        review_status: "mastered"
      }
    ],
    quizzes: [
      {
        id: "qq_photo_1",
        document_id: "doc_photosynthesis",
        question_text: "Which molecule acts as the initial electron donor in the light reactions, getting split to release oxygen?",
        options_array: [
          "Carbon dioxide (CO₂)",
          "Water (H₂O)",
          "Glucose (C₆H₁₂O₆)",
          "Adenosine triphosphate (ATP)"
        ],
        correct_option_index: 1,
        explanation: "Water is split by the oxygen-evolving complex of photosystem II to retrieve electrons, generating hydrogen ions and gaseous oxygen."
      },
      {
        id: "qq_photo_2",
        document_id: "doc_photosynthesis",
        question_text: "What takes place during the Calvin cycle of photosynthesis?",
        options_array: [
          "Solar photons excite green pigments to release heat",
          "Water molecules are divided into protons and oxygen",
          "Carbon dioxide is fixed into carbohydrate sugars using ATP and NADPH",
          "ATP synthase pumps hydrogen atoms across membranes"
        ],
        correct_option_index: 2,
        explanation: "The Calvin cycle (light-independent phase) uses energy from ATP and NADPH to convert carbon dioxide into simple sugars."
      },
      {
        id: "qq_photo_3",
        document_id: "doc_photosynthesis",
        question_text: "Which color pigment is primarily responsible for absorbing light energy for photosynthesis?",
        options_array: [
          "Carotene",
          "Chlorophyll",
          "Xanthophyll",
          "Anthocyanin"
        ],
        correct_option_index: 1,
        explanation: "Chlorophyll is the primary pigment system that absorbs blue and red wavelengths, reflecting green light back."
      }
    ]
  },
  {
    document: {
      id: "doc_quadratic",
      user_id: "user_test",
      title: "Quadratic Equations",
      raw_text_content: "A quadratic equation is a second-order polynomial equation in a single variable x, with the general standard formula ax² + bx + c = 0, where high-order coefficient 'a' cannot equal zero. The graphical representation of a quadratic function on a coordinate system is a symmetrical parabolic curve. Key features of a parabola include its vertex (the maximum or minimum extremum point), its y-intercept, and its horizontal roots (or x-intercepts). One of the most famous tools to find these roots is the quadratic formula which introduces the discriminant, D = b² - 4ac. The discriminant determines whether roots are real-rational, real-repeated, or complex-conjugate numbers, depending on whether D is positive, zero, or negative.",
      upload_date: "2026-06-13"
    },
    summary: {
      id: "sum_quadratic",
      document_id: "doc_quadratic",
      quick_read_json: [
        "Quadratic equations represent second-order mathematical expressions of form ax² + bx + c = 0.",
        "The quadratic graph forms a symmetrical curved shape called a parabola.",
        "The discriminant (b² - 4ac) diagnoses the count and form of roots (real or complex).",
        "The vertex represents the turning coordinate point where the curve hits its peak or valley."
      ],
      deep_dive_json: {
        notes: [
          "Factoring, completing the square, or the quadratic formula represent the standard algebraic methods of solution.",
          "The vertex vertical axis of symmetry is always located at x = -b / (2a).",
          "A positive discriminant means boundaries cross the horizontal x-axis twice, yielding two distinct real solutions."
        ],
        formulas: [
          "Quadratic Formula: x = (-b ± √(b² - 4ac)) / (2a)",
          "Discriminant: D = b² - 4ac",
          "Axis of Symmetry: x = -b / (2a)"
        ],
        definitions: [
          { term: "Parabola", definition: "A symmetrical curve shaped like a bowl or arch, representing quadratic paths." },
          { term: "Discriminant", definition: "The mathematical expression b² - 4ac used to find root properties." },
          { term: "Vertex", definition: "The peak or valley turning coordinate of a parabolic arc." }
        ]
      },
      eli5_text: "Imagine kicking a soccer ball high in the air! It goes up, slows down, curves beautifully at its highest peek (the vertex), and then arches back down to the ground. That symmetrical flight path forms a 'Parabola' curve, and a quadratic equation is the magical algebra code that predicts exactly where the ball will land!"
    },
    flashcards: [
      {
        id: "fc_quad_1",
        document_id: "doc_quadratic",
        question_text: "What equation shape represents all quadratic functions?",
        answer_text: "A parabola (symmetrical bowl or arch).",
        review_status: "mastered"
      },
      {
        id: "fc_quad_2",
        document_id: "doc_quadratic",
        question_text: "What does a negative discriminant (b² - 4ac < 0) mean?",
        answer_text: "There are no real roots; the solutions are complex or imaginary.",
        review_status: "learning"
      },
      {
        id: "fc_quad_3",
        document_id: "doc_quadratic",
        question_text: "What is the formula for the axis of symmetry of a standard quadratic graph?",
        answer_text: "x = -b / (2a)",
        review_status: "learning"
      }
    ],
    quizzes: [
      {
        id: "qq_quad_1",
        document_id: "doc_quadratic",
        question_text: "What value of discriminant (b² - 4ac) results in exactly one repeated real root?",
        options_array: [
          "A positive number",
          "Exactly zero",
          "A negative number",
          "An imaginary number"
        ],
        correct_option_index: 1,
        explanation: "When D = 0, the quadratic formula holds ±0, which collapses the double roots into one rational root x = -b / (2a)."
      },
      {
        id: "qq_quad_2",
        document_id: "doc_quadratic",
        question_text: "Which algebraic shape does a quadratic equation make on a plot chart?",
        options_array: [
          "A straight diagonal line",
          "A perfect round circle",
          "A clean symmetrical parabola",
          "A sharp step curve"
        ],
        correct_option_index: 2,
        explanation: "A quadratic equation (degree 2 polynomial) graph is always mapped as a parabola."
      }
    ]
  }
];
